export type PaymentMethod = 'CASH' | 'CREDIT' | 'CARD_LATER';
export type MasterOrderStatus = 'PLACED'|'WAITING_MERCHANT_ACCEPTANCE'|'PARTIALLY_ACCEPTED'|'ACCEPTED'|'PREPARING'|'READY_FOR_PICKUP'|'PICKED_UP'|'DELIVERED'|'CUSTOMER_DECISION_REQUIRED'|'RESOLUTION_REQUIRED'|'PARTIALLY_CANCELLED'|'CANCELLED'|'DISPUTED_REVIEW';
export type SubOrderStatus = 'PENDING'|'PENDING_TIMEOUT'|'ACCEPTED_WAITING_GROUP'|'ACCEPTED'|'REJECTED'|'PREPARING'|'READY'|'HANDED_OFF'|'CANCELLED';
